server:
  port: ${PORT:1234}  # Cổng mặc định cho ứng dụng Spring Boot
  servlet:
    context-path: /app  # Đường dẫn context cho ứng dụng

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: ${DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ssZ}
    time-zone: ${TIME_ZONE:Asia/Ho_Chi_Minh}
    default-property-inclusion: non_null
  application:
    name: ${APPLICATION_NAME:zimji-system-backend}
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 200MB
  messages:
    basename: language/message
    encoding: UTF-8
    cache-duration: -1
  kafka:
    bootstrap-servers: ${KAFKA_URL:172.16.101.36:9092}

logging:
  level:
    io.eventuate: debug
    io.eventuate.tram: trace
    org.springframework.orm.jpa: trace
    org.hibernate.SQL: debug
    org.springframework.jdbc.core: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace